# Generated by Django 4.1.2 on 2022-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myworks',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myworks',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myworks',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
