# Generated by Django 4.1.2 on 2022-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Site', '0002_myworks_category_myworks_client_myworks_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='myworks',
            options={'ordering': ['-project_date']},
        ),
    ]
