# Generated by Django 4.0.3 on 2022-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_Site', '0003_contact_alter_myworks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
